apiVersion: v1
kind: Service
metadata:
  name: {{ include "nebulacr.fullname" . }}-registry
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nebulacr.registry.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.registry.port }}
      targetPort: http
      protocol: TCP
    - name: metrics
      port: {{ .Values.registry.metricsPort }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "nebulacr.registry.selectorLabels" . | nindent 4 }}
